In [1]:
import numpy as np
import time
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i] [i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
        print(x)
    return x, max_iterations

In [2]:
A = np.array([
    [10, -1,  2,  0,  0],
    [-1, 11, -1,  3,  0],
    [ 2, -1, 10, -1,  0],
    [ 0,  3, -1,  8, -2],
    [ 0,  0,  0, -2,  9],
], dtype=float)

b = np.array([14, 30, 26, 25, 37], dtype=float)

x0=np.zeros_like(b)
tol=1e-6
max_iterations = 100

start = time.perf_counter()

solution, iterations= jacobi(A, b, x0, tol, max_iterations)

end=time.perf_counter()
elapsed_time=end - start

print(f"solution: {solution}")
print(f"iterations: {iterations}")
print(f"time: {elapsed_time: .6e} seconds")


[1.4        2.72727273 2.6        3.125      4.11111111]
[1.15272727 2.23863636 2.90522727 3.45505051 4.80555556]
[1.04281818 2.15389118 2.93882323 3.85005366 4.87890011]
[1.02762447 2.03922549 2.99183085 3.90436874 4.96667859]
[1.00555638 2.02784992 2.98883453 3.97593894 4.97874861]
[1.00501809 2.00605219 2.99926761 3.98284775 4.9946531 ]
[1.0007517  2.0050675  2.99788638 3.99630216 4.99618839]
[1.00092947 2.00088469 2.99998663 3.99688258 4.99917826]
[1.00009114 2.00093349 2.99959083 3.99946113 4.99930724]
[1.00017518 2.00011805 3.00002123 3.99942561 4.99988025]
[1.00000756 2.00017451 2.99991933 3.99992845 4.99987236]
[1.00003358 2.00001287 3.00000878 3.99989256 4.9999841 ]
[0.99999953 2.00003315 2.99998383 3.9999923  4.99997613]
[1.00000655 2.00000059 3.00000264 3.99997958 4.99999829]
[0.99999953 2.00000641 2.99999671 3.99999968 4.99999546]
[1.0000013  1.99999974 3.0000007  3.99999605 4.99999993]
[0.99999983 2.00000126 2.99999932 4.00000017 4.99999912]
[1.00000026 1.99999988 3.000000

In [3]:
import numpy as np
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = x.copy()
        
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i+1,n))
            x_new[i] = (b[i] - s1 - s2) / A[i] [i]
        if np.linalg.norm(x_new - x, ord= np.inf) < tol:
            return x_new, k
        x=x_new
        print(x)
    return x, max_iterations

In [4]:
A = np.array([
    [10, -1,  2,  0,  0],
    [-1, 11, -1,  3,  0],
    [ 2, -1, 10, -1,  0],
    [ 0,  3, -1,  8, -2],
    [ 0,  0,  0, -2,  9],
], dtype=float)

b = np.array([14, 30, 26, 25, 37], dtype=float)

x0=np.zeros_like(b)
tol=1e-6
max_iterations = 100

start = time.perf_counter()

solution, iterations= gauss_seidel(A, b, x0, tol, max_iterations)

end=time.perf_counter()
elapsed_time=end - start

print(f"solution: {solution}")
print(f"iterations: {iterations}")
print(f"time: {elapsed_time: .6e} seconds")

[1.4        2.85454545 2.60545455 2.38022727 4.64005051]
[1.16436364 2.42083058 2.84723306 3.73310529 4.94069006]
[1.07263645 2.06550488 2.96533373 3.9562749  4.99028331]
[1.01348374 2.00999934 2.99393068 3.99306241 4.99845831]
[1.0022138  2.00154157 2.99901764 3.9989137  4.9997586 ]
[1.00035063 2.00023883 2.99984513 3.99983073 4.99996238]
[1.00005486 2.00003707 2.99997581 3.99997367 4.99999415]
[1.00000855 2.00000576 2.99999623 3.99999591 4.99999909]
[1.00000133 2.00000089 2.99999941 3.99999936 4.99999986]
[1.00000021 2.00000014 2.99999991 3.9999999  4.99999998]
solution: [1.00000003 2.00000002 2.99999999 3.99999998 5.        ]
iterations: 10
time:  5.891830e-03 seconds


In [5]:
import numpy as np
import time
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i] [i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
        print(x)
    return x, max_iterations

In [6]:
A = np.array([
    [1, 2, 3, 0, 0],
    [2, 1, 2, 3, 0],
    [3, 2, 1, 2, 3],
    [0, 3, 2, 1, 2],
    [0, 0, 3, 2, 1],
], dtype=float)

b = np.array([14, 22, 33, 26, 22], dtype=float)

x0=np.zeros_like(b)
tol=1e-6
max_iterations = 100

start = time.perf_counter()

solution, iterations= jacobi(A, b, x0, tol, max_iterations)

end=time.perf_counter()
elapsed_time=end - start

print(f"solution: {solution}")
print(f"iterations: {iterations}")
print(f"time: {elapsed_time: .6e} seconds")


[14. 22. 33. 26. 22.]
[-129. -150. -171. -150. -129.]
[ 827. 1072. 1407. 1076.  835.]
[-6351. -7674. -9249. -7674. -6351.]
[43109. 54244. 68835. 54248. 43117.]
[-314979. -386610. -475629. -386610. -314979.]
[2200121. 2741068. 3436347. 2741072. 2200129.]
[-15791163. -19496130. -24164997. -19496130. -15791163.]
[1.11487265e+08 1.38400732e+08 1.72731531e+08 1.38400736e+08
 1.11487273e+08]
[-7.94996043e+08 -9.83639778e+08 -1.22252652e+09 -9.83639778e+08
 -7.94996043e+08]
[5.63485912e+09 6.98596448e+09 8.70453540e+09 6.98596448e+09
 5.63485913e+09]
[-4.00855351e+10 -4.96366825e+10 -6.17530126e+10 -4.96366825e+10
 -4.00855351e+10]
[2.84532403e+11 3.52587143e+11 4.39059941e+11 3.52587143e+11
 2.84532403e+11]
[-2.02235411e+12 -2.50494612e+12 -3.11754299e+12 -2.50494612e+12
 -2.02235411e+12]
[1.43625212e+13 1.77946325e+13 2.21539091e+13 1.77946325e+13
 1.43625212e+13]
[-1.02050992e+14 -1.26416758e+14 -1.57353657e+14 -1.26416758e+14
 -1.02050992e+14]
[7.24894489e+14 8.98059574e+14 1.11797299e+15

In [7]:
import numpy as np
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = x.copy()
        
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i+1,n))
            x_new[i] = (b[i] - s1 - s2) / A[i] [i]
        if np.linalg.norm(x_new - x, ord= np.inf) < tol:
            return x_new, k
        x=x_new
        print(x)
    return x, max_iterations

In [8]:
A = np.array([
    [1, 2, 3, 0, 0],
    [2, 1, 2, 3, 0],
    [3, 2, 1, 2, 3],
    [0, 3, 2, 1, 2],
    [0, 0, 3, 2, 1],
], dtype=float)

b = np.array([14, 22, 33, 26, 22], dtype=float)

x0=np.zeros_like(b)
tol=1e-6
max_iterations = 100

start = time.perf_counter()

solution, iterations= gauss_seidel(A, b, x0, tol, max_iterations)

end=time.perf_counter()
elapsed_time=end - start

print(f"solution: {solution}")
print(f"iterations: {iterations}")
print(f"time: {elapsed_time: .6e} seconds")


[ 14.  -6.   3.  38. -63.]
[  17. -132.  359. -170. -715.]
[ -799.  1412.  2091. -6962.  7673.]
[ -9083.  34892. -51597. -16802. 188417.]
[  85021.  -16420. -753837. 1180126.  -98719.]
[  2294365.  -6621412.   4295667.  11470366. -35827711.]
[ 3.55837000e+05 -4.37140840e+07  1.70903091e+08 -1.39008482e+08
 -2.34692287e+08]
[-4.25281091e+08  9.25781468e+08  4.06374195e+08 -3.12070819e+09
  5.02229382e+09]
[-3.07068551e+09  1.46907472e+10 -2.89949030e+10  3.87297667e+09
  7.92387556e+10]
[ 5.76032145e+10 -6.88355531e+10 -2.80600758e+11  6.09230663e+11
 -3.76659054e+11]
[ 9.79473379e+11 -3.22543723e+12  3.42397016e+12  3.58168948e+12
 -1.74352895e+13]
[-3.82103602e+12 -9.95093673e+12  7.65074709e+13 -8.82915527e+13
 -5.29393073e+13]
[-2.09620539e+14  5.31100795e+14 -9.79389447e+13 -1.29154588e+15
  2.87690860e+15]
[-7.68384756e+14  5.60728504e+15 -1.49570498e+16  7.33842737e+15
  3.01942948e+16]
[ 3.36565794e+16 -5.94143413e+16 -8.74007948e+16  2.92656024e+17
 -3.23109664e+17]
[ 3.8103106